# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  reward:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
        # Reward the user who opened the PR with cryptocurrency       
      - uses: perkexchange/github-action@v0.11-alpha
        name: Perk.Exchange Reward
        with:
            campaignSecret: ${{ secrets.PERKEXCHANGE_CAMPAIGNSECRET }}
            userId: ${{ github.event.pull_request.user.id }}
            amount: 1
